// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Profesori_Meditatii.Data;

#nullable disable

namespace Profesori_Meditatii.Migrations
{
    [DbContext(typeof(Profesori_MeditatiiContext))]
    [Migration("20250110142216_ProfesorMaterie")]
    partial class ProfesorMaterie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Profesori_Meditatii.Models.Materie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NumeMaterie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Materie");
                });

            modelBuilder.Entity("Profesori_Meditatii.Models.Profesor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("MaterieID")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TarifulPeOra")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("ID");

                    b.HasIndex("MaterieID");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("Profesori_Meditatii.Models.ProfesorMaterie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaterieID")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaterieID");

                    b.HasIndex("ProfesorID");

                    b.ToTable("ProfesorMaterie");
                });

            modelBuilder.Entity("Profesori_Meditatii.Models.Profesor", b =>
                {
                    b.HasOne("Profesori_Meditatii.Models.Materie", "Materie")
                        .WithMany("Profesori")
                        .HasForeignKey("MaterieID");

                    b.Navigation("Materie");
                });

            modelBuilder.Entity("Profesori_Meditatii.Models.ProfesorMaterie", b =>
                {
                    b.HasOne("Profesori_Meditatii.Models.Materie", "Materie")
                        .WithMany("ProfesorMaterii")
                        .HasForeignKey("MaterieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Profesori_Meditatii.Models.Profesor", "Profesor")
                        .WithMany("ProfesorMaterii")
                        .HasForeignKey("ProfesorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materie");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Profesori_Meditatii.Models.Materie", b =>
                {
                    b.Navigation("ProfesorMaterii");

                    b.Navigation("Profesori");
                });

            modelBuilder.Entity("Profesori_Meditatii.Models.Profesor", b =>
                {
                    b.Navigation("ProfesorMaterii");
                });
#pragma warning restore 612, 618
        }
    }
}
